# Generated by Django 3.2.7 on 2021-11-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='companydata')),
            ],
        ),
    ]
