# Generated by Django 3.2.7 on 2021-11-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('installment_plane', models.IntegerField(blank=True, default=0, verbose_name='Installment Plan (months)')),
                ('off', models.IntegerField(blank=True, default=0, verbose_name='off')),
                ('tracking_amount', models.IntegerField(blank=True, default=0)),
                ('instant', models.BooleanField(blank=True, default=False)),
                ('coid19', models.BooleanField(blank=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Main Coverage', 'Main Coverage'), ('Third Party Coverage', 'Third Party Coverage'), ('Value Added Features', 'Value Added Features')], max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('status', models.CharField(default='yes', max_length=10, verbose_name='Yes / No / any other text')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy')),
            ],
        ),
    ]
