# Generated by Django 3.2.8 on 2021-11-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211115_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='main_coverage',
            field=models.ManyToManyField(related_name='A', to='dashboard.Feature'),
        ),
        migrations.AddField(
            model_name='policy',
            name='third_party_coverage',
            field=models.ManyToManyField(related_name='B', to='dashboard.Feature'),
        ),
        migrations.AddField(
            model_name='policy',
            name='value_added_features',
            field=models.ManyToManyField(related_name='C', to='dashboard.Feature'),
        ),
    ]
