# Generated by Django 3.2.8 on 2021-11-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211118_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='status',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='main_coverage',
        ),
        migrations.AddField(
            model_name='policy',
            name='main_coverage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='A', to='dashboard.feature'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='policy',
            name='third_party_coverage',
        ),
        migrations.AddField(
            model_name='policy',
            name='third_party_coverage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='B', to='dashboard.feature'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='policy',
            name='value_added_features',
        ),
        migrations.AddField(
            model_name='policy',
            name='value_added_features',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='C', to='dashboard.feature'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeatureForPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='yes', max_length=10, verbose_name='Yes / No / any other text')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.feature')),
            ],
        ),
    ]
