# Generated by Django 3.2.8 on 2021-11-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211118_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='main_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='A', to='dashboard.feature'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='third_party_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='B', to='dashboard.feature'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='value_added_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='C', to='dashboard.feature'),
        ),
    ]
