# Generated by Django 3.2.8 on 2021-11-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211118_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureforpolicy',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy'),
            preserve_default=False,
        ),
    ]
