# Generated by Django 3.2.7 on 2021-11-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211120_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureForPolicy',
        ),
    ]
