# Generated by Django 3.2.7 on 2021-11-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_delete_featureforpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Medical Benefits'), ('2', 'Personal Accident Benefits'), ('3', 'Travel Inconvenience Benefits')], max_length=100)),
                ('feature', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('individual_amount', models.FloatField()),
                ('family_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('instant', models.BooleanField(blank=True, default=False)),
                ('coid19', models.BooleanField(blank=True, default=False)),
                ('main_coverage', models.TextField()),
                ('third_party_coverage', models.TextField()),
                ('value_added_features', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
        migrations.DeleteModel(
            name='TravelCoverage',
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='policyday',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policytravel'),
        ),
    ]
