# Generated by Django 3.2.7 on 2021-11-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211122_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comapny_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
    ]
