# Generated by Django 3.2.7 on 2021-11-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_company_redirect_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=255)),
                ('self_price', models.FloatField()),
                ('family_price', models.FloatField()),
                ('parents_price', models.FloatField()),
                ('hospitalization', models.CharField(choices=[('0.6lacto2lac', '0.6 lac to 2 lac'), ('2lacto5lac', '2 lac to 5 lac'), ('5lacto10lac', '5 lac to 10 lac')], max_length=50)),
                ('policy_documents', models.FileField(upload_to='policy_document')),
                ('claim_process', models.FileField(upload_to='policy_document')),
                ('more_features', models.TextField()),
                ('features', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.company')),
            ],
        ),
        migrations.CreateModel(
            name='LabDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policyhealth')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policyhealth')),
            ],
        ),
    ]
