# Generated by Django 3.2.7 on 2021-11-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_featurehealth_hospitalinfo_labdiscount_policyhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyhealth',
            name='coid19',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='policyhealth',
            name='instant',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
