# Generated by Django 3.2.7 on 2021-11-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_policyhealth_maternity_cover_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyhealth',
            name='off',
            field=models.FloatField(default=0),
        ),
    ]
