# Generated by Django 3.2.7 on 2021-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_policyhealth_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyhealth',
            name='family_kids_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policyhealth',
            name='family_parent_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyhealth',
            name='hospitalization',
            field=models.CharField(choices=[('60k - 2 Lac', '60k - 2 Lac'), ('2 Lac - 5 Lac', '2 Lac - 5 Lac'), ('5 Lac - 10 Lac', '5 Lac - 10 Lac')], max_length=50),
        ),
    ]
