# Generated by Django 4.0 on 2022-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_cars_carsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='claim_process',
            field=models.FileField(default='nodoc.pdf', upload_to='policy_document'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_documents',
            field=models.FileField(default='nodoc.pdf', upload_to='policy_document'),
        ),
        migrations.AddField(
            model_name='policytravel',
            name='claim_process',
            field=models.FileField(default='nodoc.pdf', upload_to='policy_document'),
        ),
        migrations.AddField(
            model_name='policytravel',
            name='policy_documents',
            field=models.FileField(default='nodoc.pdf', upload_to='policy_document'),
        ),
    ]
