# Generated by Django 4.0 on 2022-01-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_policy_claim_process_policy_policy_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='claim_process',
            field=models.FileField(blank=True, default='nodoc.pdf', null=True, upload_to='policy_document'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_documents',
            field=models.FileField(blank=True, default='nodoc.pdf', null=True, upload_to='policy_document'),
        ),
        migrations.AlterField(
            model_name='policytravel',
            name='claim_process',
            field=models.FileField(blank=True, default='nodoc.pdf', null=True, upload_to='policy_document'),
        ),
        migrations.AlterField(
            model_name='policytravel',
            name='policy_documents',
            field=models.FileField(blank=True, default='nodoc.pdf', null=True, upload_to='policy_document'),
        ),
    ]
