# Generated by Django 3.2.7 on 2021-11-15 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_auto_20211115_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquirer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('form_data', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy')),
            ],
        ),
    ]
