# Generated by Django 3.2.7 on 2021-11-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211115_2205'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_owner_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('servey_location_address', models.CharField(max_length=25)),
                ('car_registeration_number', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
                ('form_data', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policy')),
            ],
        ),
    ]
