# Generated by Django 3.2.7 on 2021-11-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_buypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirer',
            name='policy_type',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquirer',
            name='policy',
            field=models.CharField(max_length=255),
        ),
    ]
