# Generated by Django 3.2.7 on 2021-11-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_company_comapny_name'),
        ('frontend', '0003_auto_20211123_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPolicyTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=100)),
                ('date_of_issue', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('residance_address', models.CharField(max_length=100)),
                ('city_residance', models.CharField(max_length=100)),
                ('travel_from', models.CharField(max_length=100)),
                ('travel_to', models.CharField(max_length=100)),
                ('other_family_members', models.TextField()),
                ('form_data', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policytravel')),
            ],
        ),
    ]
