# Generated by Django 3.2.7 on 2021-12-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20211202_2058'),
        ('frontend', '0005_auto_20211125_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPolicyHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=100)),
                ('date_of_issue', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('residance_address', models.CharField(max_length=100)),
                ('city_residance', models.CharField(max_length=100)),
                ('other_family_members', models.TextField()),
                ('form_data', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.policytravel')),
            ],
        ),
    ]
