# Generated by Django 4.0 on 2022-01-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_buypolicyhealth_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypolicyhealth',
            name='maternity_cover_price',
            field=models.BooleanField(default=False),
        ),
    ]
