# Generated by Django 4.0 on 2022-01-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_buypolicyhealth_maternity_cover_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirer',
            name='qoutId',
            field=models.CharField(default='BS000252', max_length=100),
        ),
    ]
