# Generated by Django 4.0 on 2022-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_inquirer_qoutid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypolicy',
            name='quoteID',
            field=models.CharField(default='VF25001441', max_length=100),
        ),
        migrations.AddField(
            model_name='buypolicyhealth',
            name='quoteID',
            field=models.CharField(default='HQ25001441', max_length=100),
        ),
        migrations.AddField(
            model_name='buypolicytravel',
            name='quoteID',
            field=models.CharField(default='RD25001441', max_length=100),
        ),
    ]
